#!/bin/bash

# Read the next command from the specified command queue
#
# Usage:  get_next <cmd_queue>

# Get the name of the command queue
cmd_queue=$1

# Construct the name of the queue index file
next_cmd=${cmd_queue}_next

# If there is no cmd_queue file, quit
if [[ ! -r $cmd_queue ]]; then echo "$cmd_queue does not exist"; exit 1; fi

# If there is no queue index file, create it
if [[ ! -r $next_cmd ]]; then echo 1 > $next_cmd; fi

# Get the number of cmds in the queue
ncmds=`grep -v -e '^\s*#' -e '^\s*$' < $cmd_queue | wc -l`

# Get the index of the next command to return
n=$(< $next_cmd)

# Wrap around when we've gone too far
if ((n > ncmds)); then ((n=1)); fi

# Retrieve the next cmd
#cmd=`grep -v -e '^\s*#' -e '^\s*$' < $cmd_queue | head -n $n | tail -n 1`
# Output the next cmd
grep -v -e '^\s*#' -e '^\s*$' < $cmd_queue | head -n $n | tail -n 1

# Advance the index
(( n++ ))
echo $n > $next_cmd

# Output the cmd text
#echo ${cmd}
